version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - mariadb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: personal_book
      POSTGRES_USER: personal_book
      POSTGRES_PASSWORD: 3BYu5gQBybJ3PSh

volumes:
  mariadb_data:
