version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_DATABASE: personal_book
      MARIADB_USER: personal_book
      MARIADB_PASSWORD: 3BYu5gQBybJ3PSh

volumes:
  mariadb_data:
