// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./components/AccountList.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    ElAside: typeof import('~icons/el/aside')['default']
    ElContainer: typeof import('~icons/el/container')['default']
    ElDropdown: typeof import('~icons/el/dropdown')['default']
    ElDropdownItem: typeof import('~icons/el/dropdown-item')['default']
    ElDropdownMenu: typeof import('~icons/el/dropdown-menu')['default']
    ElHeader: typeof import('~icons/el/header')['default']
    ElIcon: typeof import('~icons/el/icon')['default']
    ElMenu: typeof import('~icons/el/menu')['default']
    ElMenuItem: typeof import('~icons/el/menu-item')['default']
    ElMenuItemGroup: typeof import('~icons/el/menu-item-group')['default']
    ElSubMenu: typeof import('~icons/el/sub-menu')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    README: typeof import('./components/README.md')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}

export { }
